version: '3'
services:
    todo-db:
        build: todo-db
        ports:
          - "3306:3306"
        environment:
          MYSQL_USER: guest
          MYSQL_PASSWORD: Guest0000!
          MYSQL_DATABASE: todoapp   
    booster:
        copy:
          - source: '../../booster'
          - destination: '/booster'
        build: Booster
        ports:
          -"3000:3000"
   
    stage2:
        build: stage2
        ports:
          - "80:80"
  
    cargo-db:
        build: cargo-db
        ports:
          - "27017:27017"
          - "28018:28018"  
  
    cargo:
        build: cargo
        ports:
          - "8080:8080"

       
