apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: booster
  name: booster
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: booster
    spec:
      containers:
      - image: morawi/missiontomars.booster:0.1
        name: booster
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
