apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: cargo-db
  name: cargo-db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cargo-db
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          value: cargo
        image: morawi/missiontomars.cargo-db:0.1
        name: cargo-db
        ports:
        - containerPort: 27017
        - containerPort: 28018
        resources: {}
      restartPolicy: Always
status: {}
