apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: cargo
  name: cargo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cargo
    spec:
      containers:
      - image: morawi/missiontomars.cargo:0.1
        name: cargo
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
